[[repos]]
repo = "builtin"
hooks = [
  { id = "check-json" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
]

[[repos]]
repo = "local"
hooks = [
  {
    id ="madlib-format",
    name="madlib format",
    entry="bash -c 'for x in \"$@\"; do madlib format -i \"$x\" --fix; done' --",
    language="system",
    files = "\\.mad$"
  },
  {
    id ="madlib-readme",
    name="madlib readme",
    entry="madlib run src/Cli.mad -- -i README.raw.md -o README.md --repo brekk/pyrite --force",
    language="system",
    files = "README\\.raw\\.md$|madlib\\.json$",
    verbose=true
  },
  {
    id ="madlib-test",
    name="madlib test",
    entry="madlib test",
    language="system",
    files = "\\.spec\\.mad$",
    pass_filenames = false
  },
]
